spring:
  application:
    name: edu-tracker-admin
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /edu-tracker/admin/
    host: slj.demodev.cc
  port: 7655

minio:
  accessKey: admin
  secretKey: password
  endpoint: http://minio:9000

sendgrid:
  api:
    key: ${SG_KEY}
    from: ${SG_FROM}