spring:
  application:
    name: edu-tracker-admin
  datasource:
    url: jdbc:mysql://localhost:3306/edutracker
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /edu-tracker/admin/
  host: localhost
  port: 8080

minio:
  accessKey: admin
  secretKey: password
  endpoint: http://minio:9000

sendgrid:
  api:
    key: ${SG_KEY}
    from: ${SG_FROM}